# Generated by Django 3.2.7 on 2021-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('school', models.CharField(db_collation='utf8_general_ci', max_length=200)),
                ('area', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('grade', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('student_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.CharField(db_collation='utf8_bin', max_length=15, primary_key=True, serialize=False)),
                ('class_id', models.CharField(db_collation='utf8_general_ci', max_length=15)),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=40)),
                ('pin', models.CharField(db_collation='utf8_general_ci', max_length=4)),
                ('password', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('level', models.IntegerField()),
                ('last_login_time', models.DateTimeField()),
                ('user_name', models.CharField(db_collation='utf8_general_ci', max_length=100)),
            ],
        ),
    ]
